### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by DerBeutlin** [matrix-hacks/matrix-puppet-signal#25]
I constantly get the following error
```

opening provisioning socket https://textsecure-service-ca.whispersystems.org:80


/opt/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:224


      throw ex;


      ^



Error: certificate has expired


    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)


    at TLSSocket.emit (events.js:203:13)


    at TLSSocket._finishInit (_tls_wrap.js:792:8)


    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)


Emitted 'error' event at:


    at WebSocket.finalize (/opt/matrix-puppet-signal/node_modules/ws/lib/WebSocket.js:182:41)


    at ClientRequest.<anonymous> (/opt/matrix-puppet-signal/node_modules/ws/lib/WebSocket.js:647:10)


    at ClientRequest.emit (events.js:203:13)


    at TLSSocket.socketErrorListener (_http_client.js:399:9)


    at TLSSocket.emit (events.js:203:13)


    at emitErrorNT (internal/streams/destroy.js:91:8)


    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)


    at processTicksAndRejections (internal/process/task_queues.js:77:11) {


  code: 'CERT_HAS_EXPIRED'


}
```
When I try to open the link in the browser I get the same certificate warning.
Is this related to using the `v0.39.0` version which is by now pretty old?

**Comment by nr23730** [comment]
It's not really an expired certificate. It's more that they applied a change they did to their clients some time ago now to their server implementation: signalapp/Signal-Desktop@50c470e53d91e4e0ecb075a0086b409d9acbce95
