### ISSUE TITLE
signal-client module not found

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [matrix-hacks/matrix-puppet-signal#27]
Did a fresh checkout, ran `npm install` (which succeeded) and then I still get a module not found exception:

    feedc0de@somewhere:/opt/matrix-puppet-signal$ npm install signal-client
    npm WARN matrix-puppet-signal@1.1.0 No repository field.
    
    + signal-client@1.0.6
    updated 2 packages in 27.596s
    feedc0de@scw-admiring-ishizaka:/opt/matrix-puppet-signal$ npm run link
    
    > matrix-puppet-signal@1.1.0 link /opt/matrix-puppet-signal
    > node -e "new (require('signal-client'))('matrix').link()"
    
    internal/modules/cjs/loader.js:797
        throw err;
        ^
    
    Error: Cannot find module '/opt/matrix-puppet-signal/node_modules/signal-desktop/components/long/dist/Long'
    Require stack:
    - /opt/matrix-puppet-signal/node_modules/signal-client/index.js
    - /opt/matrix-puppet-signal/[eval]
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
        at Function.Module._load (internal/modules/cjs/loader.js:687:27)
        at Module.require (internal/modules/cjs/loader.js:849:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at signalRequire (/opt/matrix-puppet-signal/node_modules/signal-client/index.js:14:35)
        at Object.<anonymous> (/opt/matrix-puppet-signal/node_modules/signal-client/index.js:78:16)
        at Module._compile (internal/modules/cjs/loader.js:956:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
        at Module.load (internal/modules/cjs/loader.js:812:32)
        at Function.Module._load (internal/modules/cjs/loader.js:724:14)
        at Module.require (internal/modules/cjs/loader.js:849:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at [eval]:1:6
        at Script.runInThisContext (vm.js:116:20)
        at Object.runInThisContext (vm.js:306:38)
        at Object.<anonymous> ([eval]-wrapper:9:26) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/opt/matrix-puppet-signal/node_modules/signal-client/index.js',
        '/opt/matrix-puppet-signal/[eval]'
      ]
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! matrix-puppet-signal@1.1.0 link: `node -e "new (require('signal-client'))('matrix').link()"`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the matrix-puppet-signal@1.1.0 link script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/feedc0de/.npm/_logs/2019-10-23T15_54_23_299Z-debug.log

I'm using an arch installation which is up-to-date, nodejs and npm provided by the repositories.

**Comment by nr23730** [comment]
This should be resolved with Version 2.0 that I just uploaded.
