### ISSUE TITLE
503 error getting own profile

### ISSUE THREAD

**Issue by RAOF** [matrix-hacks/matrix-puppet-signal#40]
Every two minutes or so, the bridge spews some errors into syslog (log lightly edited to remove my phone number):
```
Jan 30 03:43:11 signal-matrix-bridge matrix-puppet-signal[17265]: INFO  2020-01-30T03:43:11.027Z refreshSenderCertificate: Getting new certificate...
Jan 30 03:43:11 signal-matrix-bridge matrix-puppet-signal[17265]: INFO  2020-01-30T03:43:11.027Z GET https://textsecure-service.whispersystems.org/v1/certificate/delivery
Jan 30 03:43:11 signal-matrix-bridge matrix-puppet-signal[17265]: INFO  2020-01-30T03:43:11.527Z Sending a keepalive message
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: ERROR 2020-01-30T03:43:12.280Z GET https://textsecure-service.whispersystems.org/v1/certificate/delivery 503 Error
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: ERROR 2020-01-30T03:43:12.280Z refreshSenderCertificate: Get failed. Trying again in two minutes... HTTPError: promiseAjax: error response; code: 503
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at HTTPError (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:379:13)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at resultPromise.then.result (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:335:13)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: Original stack:
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: Error
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at _outerAjax (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:373:19)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at _ajax (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:476:14)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at Object.getSenderCertificate (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:531:14)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at run (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:65:44)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at Timeout.runWhenOnline [as _onTimeout] (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:88:7)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at ontimeout (timers.js:436:11)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at tryOnTimeout (timers.js:300:5)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at listOnTimeout (timers.js:263:5)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at Timer.processTimers (timers.js:223:10)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: INFO  2020-01-30T03:43:12.281Z GET https://textsecure-service.whispersystems.org/v1/profile/+<MY_PHONE_NUMBER>
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: ERROR 2020-01-30T03:43:12.575Z GET https://textsecure-service.whispersystems.org/v1/profile/+<MY_PHONE_NUMBER> 503 Error
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: ERROR 2020-01-30T03:43:12.578Z getProfile error: +<MY_PHONE_NUMBER> HTTPError: promiseAjax: error response; code: 503
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at HTTPError (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:379:13)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at resultPromise.then.result (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:335:13)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: Original stack:
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]: Error
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at _outerAjax (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:373:19)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at _ajax (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:476:14)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at Object.getProfile (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:548:14)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at MessageSender.getProfile (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:40762:24)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at getProfile (/home/signal-bridge/matrix-puppet-signal/node_modules/signal-desktop/js/models/conversations.js:1607:48)
Jan 30 03:43:12 signal-matrix-bridge matrix-puppet-signal[17265]:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Archehandoro** [comment]
Encountering the same issue. I believe is something to do with the certificate, not the profile, though. In my case, it started happening 2 days ago, after I updated Synapse to the latest version. However, it seems the code for the certificate in signal-desktop was somehow changed. At least is what comes to mind after seeing this ticket, but not sure whether they might be related: https://github.com/matrix-hacks/matrix-puppet-signal/issues/25

By the way, this issue makes the puppet to catch messages sent by myself from the Signal app in Signal, but messages from the other person/people in the conversation aren't shown. And messages sent from Riot to the room, aren't delivered to Signal.

**Comment by kennedyshead** [comment]
+1

**Comment by kennedyshead** [comment]
So any work on this?
