### ISSUE TITLE
 Invalid SignalProtocolAddress string

### ISSUE THREAD

**Issue by kennedyshead** [matrix-hacks/matrix-puppet-signal#42]
```
INFO  2020-02-18T14:44:20.526Z SignalProtocolStore: Finished caching signedPreKeys data
triggering storage ready
ERROR 2020-02-18T14:44:20.534Z Model caught error triggering storage_ready event: Error: Invalid SignalProtocolAddress string
    at Function.libsignal.SignalProtocolAddress.fromString (/home/***/src/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:35930:11)
    at new MessageReceiver (/home/***/src/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:38373:51)
    at new MessageReceiverWrapper (/home/***/src/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:39697:27)
    at Object.Whisper.events.on (/home/***/src/matrix-puppet-signal/node_modules/signal-client/index.js:837:23)
    at triggerEvents (/home/***/src/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:77:39)
    at Object.trigger (/home/***/src/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:131:17)
    at getStorageReady (/home/***/src/matrix-puppet-signal/node_modules/signal-client/index.js:315:20)
Matrix-side listening on port 8090
```

**Comment by kennedyshead** [comment]
Lol forgot to link ;)

**Comment by cvincent** [comment]
I am having this same exact failure except I definitely did link first. Any ideas?

**Comment by DerBeutlin** [comment]
> I am having this same exact failure except I definitely did link first. Any ideas?

I have the same problem but have no solution yet

**Comment by cvincent** [comment]
Additional info in case it helps. Following the error in the OP, I also have this in the output:

```
ERROR 2020-03-28T02:15:46.324Z PUT https://textsecure-service.whispersystems.org/v1/devices/unauthenticated_delivery 401 Error
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { HTTPError: promiseAjax: error response; code: 401
      at HTTPError (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:379:13)
      at resultPromise.then.result (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:335:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  Original stack:
  Error
      at _outerAjax (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:373:19)
      at _ajax (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:476:14)
      at Object.registerSupportForUnauthenticatedDelivery (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:540:14)
      at Object.Whisper.events.on (/matrix-puppet-signal/node_modules/signal-client/index.js:817:16)
      at triggerEvents (/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:77:39)
      at Object.trigger (/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:131:17)
      at getStorageReady (/matrix-puppet-signal/node_modules/signal-client/index.js:315:20)
    name: 'HTTPError',
    code: 401,
    response: 'Credentials are required to access this resource.' } }  reason:  { HTTPError: promiseAjax: error response; code: 401
    at HTTPError (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:379:13)
    at resultPromise.then.result (/matrix-puppet-signal/node_modules/signal-desktop/js/modules/web_api.js:335:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Also, when I link the device, it never gets to `SQL channel job 138`, but it does say `registration done`. Here is where it ends before stopping (even leaving it overnight to be sure it wasn't just taking a long time):

```
INFO  2020-03-28T22:36:05.242Z SQL channel job 132 (createOrUpdatePreKey) succeeded in 9553ms
INFO  2020-03-28T22:36:05.351Z SQL channel job 133 (createOrUpdateSignedPreKey) succeeded in 9661ms
INFO  2020-03-28T22:36:05.497Z SQL channel job 134 (createOrUpdateSignedPreKey) succeeded in 9744ms
INFO  2020-03-28T22:36:05.498Z registration done
INFO  2020-03-28T22:36:05.593Z SQL channel job 135 (saveConversation) succeeded in 87ms
INFO  2020-03-28T22:36:05.595Z dispatching registration event
INFO  2020-03-28T22:36:05.682Z SQL channel job 136 (createOrUpdateItem) succeeded in 88ms
INFO  2020-03-28T22:36:05.807Z SQL channel job 137 (createOrUpdateItem) succeeded in 212ms
```

I am pretty sure one of my attempts to get this working did actually get to `138`, but not anymore.

Hoping someone can point me in the right direction, I'd really like to stop using the Electron-based desktop app that's taking days off my CPU fan's life.
