### ISSUE TITLE
Error: could not determine third party room id!

### ISSUE THREAD

**Issue by kennedyshead** [matrix-hacks/matrix-puppet-signal#43]
```
Error in handleMatrixEvent { Error: could not determine third party room id!
    at App._handleMatrixMessageEvent (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1034:13)
    at App.handleMatrixMessageEvent (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1015:25)
    at App.handleMatrixEvent (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1007:19)
    at Bridge._onConsume (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/lib/bridge.js:872:26)
    at tryCatcher (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/knutas/src/matrix-puppet-signal/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by nr23730** [comment]
Should be resolved by updating matrix-puppet-bridge dependency.
