### ISSUE TITLE
Error: This room is configured to use encryption, but your client does not support encryption.

### ISSUE THREAD

**Issue by jeena** [matrix-hacks/matrix-puppet-signal#54]
I installed the bridge and everything worked well until I realized that the rooms the bot creates are unencrypted, which kind of defeats the purpose of communicating with people via Signal. So I went in and set the first room to encrypted. Since then I'm not able to communicate with that room. I'm getting the error:

```
Error in handleThirdPartyRoomMessage Error: This room is configured to use encryption, but your client does not support encryption.
    at _encryptEventIfNeeded (/home/jeena/matrix-puppet-signal/node_modules/matrix-js-sdk/lib/client.js:2660:11)
    at /home/jeena/matrix-puppet-signal/node_modules/matrix-js-sdk/lib/client.js:2544:31
    at async App._handleThirdPartyRoomMessage (/home/jeena/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1136:12)
...
```
... and so on. Like the UI says it's impossible to revert the encryption on a room. Therefor I thought I would delete the room and let the bot recreate it (I don't care about the previous data in it). But there is no way to delete a room. Then I found a script which would do it via the API https://gist.github.com/karl007/521f6ab84a398ee27118ab89aae7a9dc but when I run it it can't kick the @signalbot:jeena.net from the room even though my user is an admin user. I was able to kick the other user @signal_=2b46223947758:jeena.net from it but not the @signalbot:jeena.net user. This means that I can't uso https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md to restart the room.

I didn't anticipate those problems and I'm a bit worried that I can't encrypt the rooms which I use to talk to Signal, this makes at least all the attachments available publicly (when I use a proxy and the URLs are logged there). I guess HTTPS encrypts at least the connection between riot and my server, but it feels kind of dirty that the messages are not "end to end" encrypted between riot and the bridge.

Anyway, does someone have an idea how I can reestablish the one room so I can use it? Or is the only way to purge everything and start over?

**Comment by jeena** [comment]
Just realized that I need to open the issue on the other repo  https://github.com/witchent/matrix-puppet-signal/issues/14
